# 基本彙集型別（Basic Collection Types）

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen=999)
import::from(magrittr, "%>%")
reticulate::use_python(readLines("./../../envar/pypath"))
```

我們已經學了基本數據型別，包括：整數、浮點、布林、字串等，但它們都是「個別」、「單一」的值，如果想處理「多個」值的話，就要將這些值放在一起形成「彙集」（Collection）。彙集有很多形式，以下介紹：元組（tuple）、串列（list）、集合（set）、字典（dictionary）。


## 元組（tuple）

### 元組的構建

```{python, include = TRUE, echo = TRUE, message = TRUE, warning = TRUE, error = TRUE, results = TRUE}
empty = ( ) # 用小括弧來建立元組，這是一個空的元組，命名為empty，類別為tuple，因為裡面沒有東西，所以長度為0。
print(type(empty), len(empty))
seasons = ("春", "夏", "秋", "冬") # 建立一個內含「四季」字串的元組，命名為seasons，長度為4。
print(seasons, len(seasons))
hetero = (1, 3.14, True, "Hi") # 建立一個內含整數、浮點、布林、字串的元組，命名為hetero。
print(hetero)
```

### 元組的索引

#### 零基索引（zero-based indexing）

元組既然是一種彙集，裡頭當然可能裝了一個以上的物件（稱作該彙集中的元素（element）或成員（member）），如果只想對其中某些特定的元素來操作的話，就要指定是哪個，也就是對其索引，而python中的索引是從0開始算的（以零為基礎），也就是說如果有10個元素照順序放在一起，第一個用0來索引、第二個用1來索引、第三個用2來索引，依此類推到第10個則用9來索引。索引方式：「彙集[索引值]」，超出範圍的索引會得到錯誤訊息。具體做法如下：
```{python, include = TRUE, echo = TRUE, message = TRUE, warning = TRUE, error = TRUE, results = TRUE}
t = ('一', '二', '三', '四', '五', '六', '七', '八', '九', '十') # 將內有十個字符的元組命名為t。
print(t[0], t[1], t[2], t[4], t[7], t[8]) # 列出排在第1, 2, 3, 5, 8, 9位置的元素。
print(t[10]) # 列出排在第11位置的元素，超出正確索引範圍，發生錯誤。
```

#### 負值索引

如果有個彙集裝了太多元素，例如超過100個，從頭往尾慢慢數要很久耶，如果我要知道最後一個元素的內容怎麼辦？至少可以有二種作法：

+ 利用函式`len( )`找出長度，將該長度-1（因為從0起算）再行索引。
+ 直接採用負值索引。

以下我們要找到一個長的元組中，倒數第1, 2, 5個位置上的元素：
```{python, include = TRUE, echo = TRUE, message = TRUE, warning = TRUE, error = TRUE, results = TRUE}
p = (3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 8, 9, 7, 9, 3, 2, 3, 8, 4, 6, 2, 6, 4, 3, 3, 8, 3, 2, 7, 9, 5, 0, 2, 8, 8, 4, 1, 9, 7, 1, 6, 9, 3, 9, 9, 3, 7, 5, 1, 0, 5, 8, 2, 0, 9, 7, 4, 9, 4, 4, 5, 9, 2, 3, 0, 7, 8, 1, 6, 4, 0, 6, 2, 8, 6, 2, 0, 8, 9, 9, 8, 6, 2, 8, 0, 3, 4, 8, 2, 5, 3, 4, 2, 1, 1, 7, 0, 6, 7, 9, 8, 2, 1, 4, 8, 0, 8, 6, 5, 1, 3, 2, 8, 2, 3, 0, 6, 6, 4, 7, 0, 9, 3, 8, 4, 4, 6, 0, 9, 5, 5, 0, 5, 8, 2, 2, 3, 1, 7, 2, 5, 3, 5, 9, 4, 0, 8, 1, 2, 8, 4, 8, 1, 1, 1, 7, 4, 5, 0, 2, 8, 4, 1, 0, 2, 7, 0, 1, 9, 3, 8, 5, 2, 1, 1, 0, 5, 5, 5, 9, 6, 4, 4, 6, 2, 2, 9, 4, 8, 9, 5, 4, 9, 3, 0, 3, 8, 1, 9, 6, 4, 4, 2, 8, 8, 1, 0, 9, 7, 5, 6, 6, 5, 9, 3, 3, 4, 4, 6, 1, 2, 8, 4, 7, 5, 6, 4, 8, 2, 3, 3, 7, 8, 6, 7, 8, 3, 1, 6, 5, 2, 7, 1, 2, 0, 1, 9, 0, 9, 1, 4, 5, 6, 4, 8, 5, 6, 6, 9, 2, 3, 4, 6, 0, 3, 4, 8, 6, 1, 0, 4, 5, 4, 3, 2, 6, 6, 4, 8, 2, 1, 3, 3, 9, 3, 6, 0, 7, 2, 6, 0, 2, 4, 9, 1, 4, 1, 2, 7, 3, 7, 2, 4, 5, 8, 7, 0, 0, 6, 6, 0, 6, 3, 1, 5, 5, 8, 8, 1, 7, 4, 8, 8, 1, 5, 2, 0, 9, 2, 0, 9, 6, 2, 8, 2, 9, 2, 5, 4, 0, 9, 1, 7, 1, 5, 3, 6, 4, 3, 6, 7, 8, 9, 2, 5, 9, 0, 3, 6, 0, 0, 1, 1, 3, 3, 0, 5, 3, 0, 5, 4, 8, 8, 2, 0, 4, 6, 6, 5, 2, 1, 3, 8, 4, 1, 4, 6, 9, 5, 1, 9, 4, 1, 5, 1, 1, 6, 0, 9, 4, 3, 3, 0, 5, 7, 2, 7, 0, 3, 6, 5, 7, 5, 9, 5, 9, 1, 9, 5, 3, 0, 9, 2, 1, 8, 6, 1, 1, 7, 3, 8, 1, 9, 3, 2, 6, 1, 1, 7, 9, 3, 1, 0, 5, 1, 1, 8, 5, 4, 8, 0, 7, 4, 4, 6, 2, 3, 7, 9, 9, 6, 2, 7, 4, 9, 5, 6, 7, 3, 5, 1, 8, 8, 5, 7, 5, 2, 7, 2, 4, 8, 9, 1, 2, 2, 7, 9, 3, 8, 1, 8, 3, 0, 1, 1, 9, 4, 9, 1, 2)
print(p[len(p)-1], p[len(p)-2], p[len(p)-5]) 
print(p[-1], p[-2], p[-5]) 
```
看來負值索引的方法更簡潔。

#### 範圍索引

範圍索引用在一次找出好幾個不同位置上的元素，方式為「彙集[起點位置:（不含）終點位置]」，索引值可以是負值，實例如下：
```{python, include = TRUE, echo = TRUE, message = TRUE, warning = TRUE, error = TRUE, results = TRUE}
print(t) # 變項t是有十個字符的元組。
print(t[2:5]) # 索引2（第3個）～不含索引5（第6個）
print(t[5:-2]) # 索引5（第6個）～不含倒數第2個
print(t[-8:7]) # 倒數第8個～不含索引7（第8個）
```


範圍索引如省略起點位置或終點位置的話，各自表示「從頭開始、直到最尾」的意思：
```{python, include = TRUE, echo = TRUE, message = TRUE, warning = TRUE, error = TRUE, results = TRUE}
print(t[:5]) # 從第一個～不含索引5（第6個）
print(t[5:]) # 從索引5（第6個）～到最後一個
print(t[:]) # 從第一個～到最後一個
```


範圍索引不一定要在位置上連續，也可以有間隔，方式為「彙集[起點位置:（不含）終點位置:間隔]」，如下：
```{python, include = TRUE, echo = TRUE, message = TRUE, warning = TRUE, error = TRUE, results = TRUE}
print(t[2:8:2]) # 索引2（第3個）～不含索引8（第9個），間隔為2。
print(t[::3]) # 從頭至尾，間隔為3。
```

### 元組算術運算

前面提及字串可以使用算術運算子的「加」（接續）和「乘」（重複），元組也可以，而且也是先乗再加：
```{python, include = TRUE, echo = TRUE, message = TRUE, warning = TRUE, error = TRUE, results = TRUE}
print(seasons + hetero * 2)
print(t[1:4] + season[::2] * 2 + hetero[-2:] * 3)
```


### 元組常用函式

```{python, include = TRUE, echo = TRUE, message = TRUE, warning = TRUE, error = TRUE, results = TRUE}
print(len(seasons), len(hetero)) # 型別相同或不同，都能回報長度。
print(max(seasons), min(seasons)) # 型別相同還能比大小。
print(max(hetero), min(hetero)) # 型別不同則無大小之分。
print(*zip(seasons, hetero)) # 將長度相同的彙集中索引位置相同者，弄成同組，再用前置星號展開。
print(*enumerate(t)) # 將索引位置與對應的元素，弄成同組，再用前置星號展開。
print(*reversed(t)) # 將元組內的元素反向排列，最前的變成最後的、最後的變成最前的。
print(sum(p)) # 將元組內的每個元素相加，求取其和。
```

### 元組常用方法

```{python, include = TRUE, echo = TRUE, message = TRUE, warning = TRUE, error = TRUE, results = TRUE}
print(p.count(3)) # 回報元組p中有幾個元素的值是3。
print(p.index(9)) # 回報元組p中原素為9最早出現在哪個索引值。
```

### 自我練習（元組）

1. 打開Jupyter或Spyder。
1. 自己建構一些元組，將學過的每個元組可用的函式和方法，至少用自己的例子執行三次，看看與自己的預期是否相同。


## 串列（list）


## 集合（set）



## 字典（dictionary）



```{python, include = TRUE, echo = TRUE, message = TRUE, warning = TRUE, error = TRUE, results = TRUE}
```


